version: "3.9"

services:
  node:
    build:
      context: ./node-23
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  deno:
    build:
      context: ./deno-2
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  bun:
    build:
      context: ./bun-1
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
